// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sywllhsxbchiyclvpzfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5d2xsaHN4YmNoaXljbHZwemZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwODE4MTIsImV4cCI6MjA3MjY1NzgxMn0.1R1XURJE4c-j8_-kafPHLZOx3jeH_YD6IngdR71G4c8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});